replay_buffer:
  capacity: 100000
  unbalace: 0.8
  batch_size: 1

training:
  epochs: 1001
  buffer_capacity: 100000
  experience_duration: 200
  batch_size: 128
  sample_size: 64

OUnoise:
  theta: 0.15
  sigma: 0.2
  dt: 0.01

actor:
  layers: [400, 300]
  stddev: 0.0005

critic:
  state_layers: [400, 300]
  action_layers: [300,]
  stddev: 0.0005
  
agent:
  gamma: 0.99
  tau: 0.001
  epsilon: 0.1
  learning_rate: 0.0001
  noise: OUnoise